-copy and pull instead of clone -rm node modules after stop service

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,15 +39,10 @@ jobs:
                         echo "Making stable copy..."
                         rsync -ar --exclude 'images' --exclude 'node_modules' kitmakesthingsv4/ kmt_stable
                         echo "Making build directory..."
-                        mkdir build_temp
+                        rsync -ar --exclude 'images' kitmakesthingsv4/ build_temp
                         echo "Moving to build directory..."
                         cd build_temp
-                        git clone git@github.com:KitHamm/kitmakesthingsv4.git
-                        echo "Copying necessary files..."
-                        cd ..
-                        cp kitmakesthingsv4/.env build_temp/kitmakesthingsv4
-                        echo "Moving to repo directory"...
-                        cd build_temp/kitmakesthingsv4
+                        git pull origin main
                         if [ ! -f .env ]; then
                           echo "File is missing. Deployment cannot continue."
                           exit 1
@@ -60,17 +55,18 @@ jobs:
                         npm run build
                         if [ $? -ne 0 ]; then
                           echo "Build failed. Exiting deployment."
-                          cd ../..
+                          cd ..
                           rm -r build_temp
                           exit 1
                         fi
                         echo "Moving to base folder..."
-                        cd ../..
+                        cd ..
                         echo "Stopping server..."
                         pm2 stop kitmakesthingsv4 || { echo "Failed to stop PM2 process"; exit 1; }
                         echo "Server stopped."
                         echo "Copying build files..."
-                        rsync -ar build_temp/kitmakesthingsv4/ kitmakesthingsv4 || { echo "Failed to copy files"; exit 1; }
+                        rm -rf kitmakesthingsv4/node_modules
+                        rsync -ar build_temp/ kitmakesthingsv4 || { echo "Failed to copy files"; exit 1; }
                         echo "Files copied."
                         echo "Starting server..."
                         pm2 start kitmakesthingsv4 || { echo "Failed to start PM2 process"; exit 1; }
