updated dir in green deploy

diff --git a/.github/workflows/greenDeploy.yml b/.github/workflows/greenDeploy.yml
--- a/.github/workflows/greenDeploy.yml
+++ b/.github/workflows/greenDeploy.yml
@@ -22,7 +22,7 @@ jobs:
                   command_timeout: 20m
                   script: |
                       echo "Moving to stable directory..."
-                      cd ../srv/www/kmt_stable || { echo "Failed to change directory to /srv/www/kmt_stable"; exit 1; }
+                      cd /srv/www/kmt_stable || { echo "Failed to change directory to /srv/www/kmt_stable"; exit 1; }
 
                       export NVM_DIR=~/.nvm || { echo "NVM_DIR not set"; exit 1; }
                       source ~/.nvm/nvm.sh || { echo "Failed to source NVM"; exit 1; }
