more logging on fetch main

diff --git a/.github/workflows/greenDeploy.yml b/.github/workflows/greenDeploy.yml
--- a/.github/workflows/greenDeploy.yml
+++ b/.github/workflows/greenDeploy.yml
@@ -28,10 +28,14 @@ jobs:
                       echo "Moving to stable directory..."
                       cd ../srv/www/kmt_stable || { echo "Failed to change directory to /srv/www/kmt_stable"; exit 1; }
 
+                      echo "Fetching main..."
+
+                      git fetch origin main:origin/main --update-head-ok || { echo "git fetch failed"; exit 1; }
+
+                      git rev-parse HEAD >/dev/null 2>&1 || { echo "No HEAD found"; exit 1; }
+                      git rev-parse origin/main >/dev/null 2>&1 || { echo "No origin/main found"; exit 1; }
+
                       echo "Checking for changes in prisma.schema..."
-
-                      git fetch origin main || { echo "git fetch failed"; exit 1; }
-
                       git diff --name-only HEAD origin/main | grep -q "prisma/schema.prisma"
                       SCHEMA_CHANGED=$?
 
